import {chromium} from '@playwright/test';
import fs from 'node:fs/promises';
const out=process.env.GOOSEN_TEST_OUTPUT||'test-results';await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1600,height:1000},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
const url=process.env.GOOSEN_TEST_URL||'http://127.0.0.1:4173';
await page.goto(url);
await page.waitForFunction(()=>window.__GOOSEN__?.getSnapshot().ready,{},{timeout:90000});
await page.waitForTimeout(1500);
await page.screenshot({path:out+'/welcome.png'});
await page.locator('#fly-button').click();
await page.waitForTimeout(1000);
const before=await page.evaluate(()=>window.__GOOSEN__.getSnapshot());
await page.keyboard.down('KeyD');await page.keyboard.down('KeyE');await page.keyboard.down('KeyW');
await page.waitForTimeout(2500);
await page.keyboard.up('KeyD');await page.keyboard.up('KeyE');await page.keyboard.up('KeyW');
await page.waitForTimeout(1500);
const after=await page.evaluate(()=>window.__GOOSEN__.getSnapshot());
await page.screenshot({path:out+'/flight.png'});
if(Math.hypot(after.flight.east-before.flight.east,after.flight.north-before.flight.north)<10)throw new Error('Flight did not move');
if(after.flight.altitude<=before.flight.altitude)throw new Error('Climb did not work');
// Pause via a real UI key; pointer lock differs between headed/headless browsers.
await page.keyboard.press('Escape');
await page.waitForFunction(()=>!window.__GOOSEN__.getSnapshot().playing);
const paused=await page.evaluate(()=>window.__GOOSEN__.getSnapshot().flight);
await page.waitForTimeout(600);
const still=await page.evaluate(()=>window.__GOOSEN__.getSnapshot().flight);
if(paused.east!==still.east||paused.north!==still.north)throw new Error('Pause failed');
await page.locator('#help-button').click();await page.locator('#help-dialog [data-close]').click();
await page.locator('#resume-button').click();await page.keyboard.press('KeyM');
await page.locator('[data-place="village"]').click();await page.waitForTimeout(800);
const village=await page.evaluate(()=>window.__GOOSEN__.getSnapshot());
if(Math.abs(village.flight.east-860)>40)throw new Error('Map reset failed');
await page.keyboard.press('KeyP');await page.waitForTimeout(400);
const [download]=await Promise.all([page.waitForEvent('download'),page.locator('#capture-button').click()]);await download.saveAs(out+'/photo.png');
await page.locator('#photo-close').click();
await page.locator('#resume-button').click();await page.waitForTimeout(3000);
const result={before,after,village,final:await page.evaluate(()=>window.__GOOSEN__.getSnapshot()),errors};
await page.close();
// Embedded browsers may prohibit pointer lock. Exercise the actual drag fallback.
const embedded=await browser.newPage({viewport:{width:1280,height:800}});
embedded.on('pageerror',e=>errors.push(String(e)));
await embedded.addInitScript(()=>{HTMLCanvasElement.prototype.requestPointerLock=()=>Promise.reject(new Error('Pointer lock unavailable in embedded browser'));});
await embedded.goto(url);await embedded.waitForFunction(()=>window.__GOOSEN__?.getSnapshot().ready,{},{timeout:90000});
await embedded.locator('#fly-button').click();await embedded.waitForTimeout(300);
const dragBefore=await embedded.evaluate(()=>window.__GOOSEN__.getSnapshot());
await embedded.mouse.move(650,400);await embedded.mouse.down();
await embedded.mouse.move(1000,350,{steps:40});await embedded.mouse.up();
await embedded.waitForTimeout(1000);
const dragAfter=await embedded.evaluate(()=>window.__GOOSEN__.getSnapshot());
if(Math.abs(dragAfter.flight.yaw-dragBefore.flight.yaw)<.05)throw new Error('Drag steering failed without pointer lock');
await embedded.keyboard.press('Escape');
await embedded.locator('#pause-dialog .close').click();
if(!(await embedded.evaluate(()=>window.__GOOSEN__.getSnapshot().playing)))throw new Error('Close pause failed to resume');
result.embedded={dragBefore,dragAfter};
await fs.writeFile(out+'/browser-report.json',JSON.stringify(result,null,2));
console.log(JSON.stringify(result,null,2));
await browser.close();if(errors.length)process.exitCode=1;
