// Record the running app itself; no generated landscape or composited UI.
import {chromium} from '@playwright/test';
import fs from 'node:fs/promises';
const output=process.env.GOOSEN_DEMO_OUTPUT||'test-results/demo';
await fs.mkdir(output,{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true});
const context=await browser.newContext({viewport:{width:1600,height:900},deviceScaleFactor:1,recordVideo:{dir:output,size:{width:1600,height:900}}});
const started=performance.now(),page=await context.newPage(),errors=[],timeline=[];
page.on('pageerror',e=>errors.push(String(e)));
const mark=label=>timeline.push({label,seconds:(performance.now()-started)/1000});
await page.goto(process.env.GOOSEN_TEST_URL||'http://127.0.0.1:4174');
await page.waitForFunction(()=>window.__GOOSEN__?.getSnapshot().ready,{},{timeout:90000});
await page.waitForTimeout(800);mark('Start view');
await page.waitForTimeout(3500);
await page.locator('#fly-button').click();mark('Harbour flight');
await page.keyboard.press('KeyR');
await page.keyboard.down('KeyW');await page.waitForTimeout(1700);await page.keyboard.up('KeyW');
await page.waitForTimeout(10300);
await page.keyboard.down('KeyD');await page.waitForTimeout(700);await page.keyboard.up('KeyD');
await page.waitForTimeout(2500);
await page.keyboard.press('KeyM');mark('Map and start points');
await page.waitForTimeout(3500);
await page.locator('[data-place="fields"]').click();mark('Fields towards village and coast');
await page.keyboard.press('KeyR');
await page.keyboard.down('KeyW');await page.waitForTimeout(2300);await page.keyboard.up('KeyW');
await page.waitForTimeout(19700);
await page.screenshot({path:output+'/poster.png'});
await page.keyboard.press('KeyP');mark('Photo mode');
await page.waitForTimeout(3500);
await page.locator('#photo-close').click();mark('End');
await page.waitForTimeout(2000);
const video=page.video(),snapshot=await page.evaluate(()=>window.__GOOSEN__.getSnapshot());
await context.close();const path=await video.path();await browser.close();
await fs.writeFile(output+'/recording.json',JSON.stringify({path,timeline,errors,snapshot},null,2));
console.log(JSON.stringify({path,timeline,errors},null,2));
if(errors.length)process.exitCode=1;
